name: Sincronizar com Hugging Face
on:
  push:
    branches: [ main, master ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main  # <- Garante que o robô baixe a ramificação certa e não um "fantasma"

      - name: Converter imagens para LFS e Enviar
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot Sincronizador"
          git lfs install
          # O parâmetro --everything força a conversão em todo o histórico de pastas
          git lfs migrate import --yes --everything --include="*.png,*.jpg,*.jpeg,*.db"
          git push --force https://GrizzlyBear25:${HF_TOKEN}@huggingface.co/spaces/GrizzlyBear25/HyperTork_ main
