name: Sincronizar com Hugging Face
on:
  push:
    branches: [ main, master ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do GitHub
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Enviar para o Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://sergioaugusto:$HF_TOKEN@huggingface.co/spaces/grizzlybear25-hypertork.hf.space main
